name: transittrack
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.2.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.2.3
  go_router: ^14.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_auth: ^5.1.2
  internet_connection_checker: ^1.0.0+1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.1
  location: ^7.0.0
  flutter_polyline_points: ^2.1.0
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  liquid_swipe: ^3.1.0
  flutter_otp_text_field: ^1.1.3+2
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  http: ^1.2.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_typeahead: ^5.2.0
  flutter_lints: ^4.0.0
  flutter_google_places_hoc081098: ^2.0.0
  envied: ^0.5.4+1
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/images/



  fonts:
    - family: Laila
      fonts:
        - asset: assets/fonts/Laila/Laila-Regular.ttf
          weight: 200
        - asset: assets/fonts/Laila/Laila-Bold.ttf
          weight: 700
  #
