// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJHjRdBIoaS0lP6i_2jaRl07i6SbK3K0',
    appId: '1:70344907648:web:13515ced001d776aecbf65',
    messagingSenderId: '70344907648',
    projectId: 'transit-track-83262',
    authDomain: 'transit-track-83262.firebaseapp.com',
    storageBucket: 'transit-track-83262.appspot.com',
    measurementId: 'G-2L6NVED34D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaj1GHbvzXvQAhaDOT1cxEirtx6bYucWA',
    appId: '1:70344907648:android:9fe06412e3d1fe86ecbf65',
    messagingSenderId: '70344907648',
    projectId: 'transit-track-83262',
    storageBucket: 'transit-track-83262.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgE_Ov5MXjHre7kC4jfl4tG546ZV5sZYM',
    appId: '1:70344907648:ios:c7a1898c16bfa8a2ecbf65',
    messagingSenderId: '70344907648',
    projectId: 'transit-track-83262',
    storageBucket: 'transit-track-83262.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgE_Ov5MXjHre7kC4jfl4tG546ZV5sZYM',
    appId: '1:70344907648:ios:c7a1898c16bfa8a2ecbf65',
    messagingSenderId: '70344907648',
    projectId: 'transit-track-83262',
    storageBucket: 'transit-track-83262.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnJHjRdBIoaS0lP6i_2jaRl07i6SbK3K0',
    appId: '1:70344907648:web:b1222322f0e5b04cecbf65',
    messagingSenderId: '70344907648',
    projectId: 'transit-track-83262',
    authDomain: 'transit-track-83262.firebaseapp.com',
    storageBucket: 'transit-track-83262.appspot.com',
    measurementId: 'G-5SLMWZD9QC',
  );
}
